config/routes.rb
Rails.application.routes.draw do
  resources :links, except: [:index, :show, :new, :create] do
  	member do
  		get 'fetch'
  	end
  end
  root 'pages#home'
  get 'about', to: 'pages#about', as: 'pages'
  get 'pocket/add', to: 'pocket#add', as: 'pocket_add'
  get 'oauth/callback', to: 'pocket#callback'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/about.html.erb
<div class="home">
	<h1>What is this?</h1>
	<p class="lead">This is a site that shows what articles on the Internet philosophers on Twitter are linking to.</p>

	<h1>How does it work?</h1>
	<p>Every ten minutes it checks my <a href="https://twitter.com/monkeyx/lists/philosophers">philosophers</a> list on Twitter and parses out any links. It picks out links heading outside Twitter and works out what they link to, saving them here for up to 30 days.</p>

	<h1>Why is my link not showing?</h1>
	<p>Only links posted by those on the <a href="https://twitter.com/monkeyx/lists/philosophers">philosophers</a> list will show. If you think you should be on this list, drop me an <a href="mailto:monkeyx@gmail.com?subject=phlinks">email</a> with a link to your Twitter profile.</p>
	<p>Some links are filtered out because the site couldn't be reached or the articles on that site are typically behind a hard paywall.</p>

	<p><%=link_to 'Home', root_url %></p>
</div>

app/views/pages/home.html.erb
<div class="home">
	<h1>Links from <a href="https://twitter.com/i/lists/<%=LIST_ID%>">philosophy Twitter</a> <%=link_to image_tag('rss.png'), root_url(:format => :rss)%></h1>
	<p class="lead"><% if @links.any? %><%=@links.count%> links. Last refreshed <%=Link.last_fetched%><% end %></p>
	<p><%=link_to image_tag('twitter.png'), "https://twitter.com/philosophylinks" %></p>
	<% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>">
              <%= value.html_safe %>
        </div>
  	<% end %>
      
	<div class="table-responsive">
		<table class="table table-striped w-auto">
		  <thead>
		    <tr>
		      <th scope="col">#</th>
		      <th scope="col">Article</th>
		      <th scope="col">User</th>
		      <th scope="col">Posted</th>
		      <th scope="col">Impact</th>
		      <th scope="col"></th>
		      <% if @admin_mode %>
		      <th scope="col" colspan="2"></th>
		      <% end %>
		    </tr>
		  </thead>
		  <tbody>
		  	<% n = 0 %>
			<% @links.page(params[:page] || 1).each do |link| %>
			<% n += 1 %>
			<%=render partial: '/links/show', locals: {n: n, link: link, admin_mode: @admin_mode}, cached: !@admin_mode %>
			<% end %>
		  </tbody>
		</table>
	</div>

	<%= paginate @links.page(params[:page] || 1) %>
<p><%=link_to 'About', pages_url %></p>
<p><%=link_to image_tag('valid-rss-rogers.png', alt: "[Valid RSS]", title: "Validate my RSS feed"), "https://validator.w3.org/feed/check.cgi?url=https%3A//phlinks.herokuapp.com/%3Fformat%3Drss" %></p>
<p><%=link_to image_tag('github.png', alt: "Available on Github", title: "Available on Github"), "https://github.com/seyedrazavi/phlinks" %></p>
</div>